version: "3.8"

services:
  nginx:
    image: nginx:$TAG
    container_name: nginx
    build: "requirements/nginx"
    env_file: .env
    restart: on-failure
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"

  wordpress:
    image: wordpress:$TAG
    container_name: wordpress
    build: "requirements/wordpress"
    env_file: .env
    restart: on-failure
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"

  mariadb:
    image: mariadb:$TAG
    container_name: mariadb
    build: "requirements/mariadb"
    env_file: .env
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"


volumes:
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/jfremond/data/wp_data'
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/jfremond/data/db_data'

networks:
  inception:
