version: '3.9'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: on-failure
    networks:
      - inception
    image: "nginx"
    working_dir: /var/www/html

networks:
  inception:
    driver: bridge