version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx
    build: "requirements/nginx"
    env_file: .env
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"

  wordpress:
    image: wordpress
    container_name: wordpress
    build: "requirements/wordpress"
    env_file: .env
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"

  mariadb:
    image: mariadb
    container_name: mariadb
    build: "requirements/mariadb"
    env_file: .env
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/jfremond/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/jfremond/data/mariadb'

networks:
  inception:
    # driver: bridge
