version: "3.3"

services:
  nginx:
    image: nginx:${TAG}
    container_name: nginx
    build: "requirements/nginx"
    env_file: .env
    restart: on-failure
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
        # condition: service_healthy
    ports:
      - "443:443"

  wordpress:
    image: wordpress:${TAG}
    container_name: wordpress
    build: "requirements/wordpress"
    env_file: .env
    restart: on-failure
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
        # condition: service_healthy
    expose:
      - "9000"

  mariadb:
    image: mariadb:${TAG}
    container_name: mariadb
    build: "requirements/mariadb"
    env_file: .env
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    # healthcheck:
    #   test ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s


volumes:
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/jfremond/data/wp_data'
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/jfremond/data/db_data'

networks:
  inception:
