version: '3.9'

services:
  nginx:
    image: "nginx"
    build: ./requirements/nginx
    ports:
      - "443:443"
    working_dir: /var/www/html
    restart: on-failure
    networks:
      - inception

networks:
  inception:
    driver: bridge

